### ISSUE TITLE
Bot should take a config for multiple rooms from one file

### ISSUE THREAD

**Issue by ckingdev** [rainbowbismuth/euphoria-py#3]
A user should be able to run a bot in multiple rooms with different configurations for each room. The configuration should be taken from one file.

rainbowbismuth, I'm happy to write this after I read over your code. If you'd like to do it, though, please feel free!

**Comment by rainbowbismuth** [comment]
My idea is there will be a borg.ini which would look something like

``` ini
[borg]
botname1 = botname_config1.ini
botname2 = botname_config2.ini
```

and then you'd start it with `python3 -m euphoria.borg`.

**Comment by rainbowbismuth** [comment]
`python3 -m euphoria.borg` is :zap: as of a85a1f52bc7c62727dfefa16366dfe40fa911a8f
